# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

locale                   : "en"
title                    : "The Data Lab"
description              : "Things you can make with data, by your friends @ IBM CODAIT"
url                      : "https://ibm-watson-data-lab.github.io"
baseurl                  : ""
repository               : "ibm-watson-data-lab/ibm-watson-data-lab.github.io"

collections:
  strategies:
    output: true
  features:
    output: true
  authors:
    output: true

# relative_permalinks: false

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - search

include:
  - _pages
