# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

locale                   : "en"
title                    : "IBM Watson Data Lab"
description              : "Things you can make with data, on the IBM Watson Data Platform"
url                      : "https://ibm-watson-data-lab.github.io"
baseurl                  : ""
repository               : "ibm-watson-data-lab/ibm-watson-data-lab.github.io"

# Set to the URL of your OpenWhisk package: https://{APIHOST}/api/v1/web/{NAMESPACE}/{PACKAGE}
owpackageurl      : "https://openwhisk.ng.bluemix.net/api/v1/web/Dev-Advocates_wdp-infrastructure/sentry"

collections:
  strategies:
    output: true
  features:
    output: true
  authors:
    output: true

# relative_permalinks: false

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - openwhisk