# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

locale                   : "en"
title                    : "IBM Watson Data Lab"
description              : "The things you can make with data, on the IBM Watson Data Platform"
url                      : "https://ibm-cds-labs.github.io"
baseurl                  : ""
repository               : "ibm-cds-labs/ibm-cds-labs.github.io"

collections:
  features:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
